### ISSUE TITLE
Hex.pm lists 0.1.0 as latest version of the SDK

### ISSUE THREAD

**Issue by janpieper** [eigr/spawn#132]
**Describe the bug**

Latest version of `spawn_sdk` on [hex.pm](https://hex.pm/packages/spawn_sdk) is `0.1.0` although newer version have been published :thinking: 

![Screenshot from 2023-01-23 17-34-30](https://user-images.githubusercontent.com/426371/214095748-c973f284-b17f-4deb-8b7e-2405a142cb28.png)

**To Reproduce**

Add `spawn_sdk` to your `mix.exs` like the following and run `mix deps.get`:

```elixir
{:spawn_sdk, ">= 0.0.0"}`
```

**Expected behavior**

Latest version (currently: `0.5.0-rc.13`) should be installed.

**Additional context**

Using `{:spawn_statestores_postgres, ">= 0.0.0"}` works fine. For that package, the latest version is `0.5.0-rc.13` on [hex.pm](https://hex.pm/packages/spawn_statestores_postgres).

**Comment by sleipnir** [comment]
Hi @janpieper 

By entering this link you will find the correct dependency you need.

https://hex.pm/packages/spawn_statestores_postgres/0.5.0-rc.13

This, at least for now, is on purpose, which is why I removed the bug label from this issue and added one to classify it correctly.

Please add the dependency explicitly as follows:

```
       {:spawn_statestores_mysql, "~> 0.5.0-rc.13"}
```

**Comment by janpieper** [comment]
This issue wasn't about `spawn_statestores_postgres` 🤔 It is about `spawn_sdk`.

**Comment by sleipnir** [comment]
> This issue wasn't about `spawn_statestores_postgres` thinking It is about `spawn_sdk`.

When we release version 0.5.0 everything will be fine. For now, to add any dependency to your project, you must declare it as I indicated.

The possible dependencies for now are:

```elixir
mix.exs

     {:spawn_sdk, "~> 0.5.0-rc.13"},

     # You can uncomment one of those dependencies if you are going to use Persistent Actors
     #{:spawn_statestores_mysql, "~> 0.5.0-rc.13"},
     #{:spawn_statestores_postgres, "~> 0.5.0-rc.13"},
     #{:spawn_statestores_mssql, "~> 0.5.0-rc.13"},
     #{:spawn_statestores_cockroachdb, "~> 0.5.0-rc.13"},
     #{:spawn_statestores_sqlite, "~> 0.5.0-rc.13"}
```
