### ISSUE TITLE
[BUG] Gossip Strategy fail

### ISSUE THREAD

**Issue by sleipnir** [eigr/spawn#133]
**Describe the bug**

When starting the Proxy with the variable PROXY_CLUSTER_STRATEGY=gossip the system fails to start with the error below:

```elixir
Could not start application proxy: exited in: Proxy.Application.start(:normal, [])
     ** (EXIT) an exception was raised:
         ** (RuntimeError) Failed to start Proxy Application: {:error, {:shutdown, {:failed_to_start_child, Proxy.Supervisor, {:shutdown, {:failed_to_start_child, Sidecar.Supervisor, {:shutdown, {:failed_to_start_child, Sidecar.ProcessSupervisor , {:shutdown, {:failed_to_start_child, :"Spawn.Cluster", {:shutdown, {:failed_to_start_child, Cluster.Supervisor, {:shutdown, {:failed_to_start_child, :proxy, {{:badmatch, {:error, :eaddrinuse }}, [{Cluster.Strategy.Gossip, :init, 1, [file: 'lib/strategy/gossip.ex', line: 126]}, {:gen_server, :init_it, 2, [file: 'gen_server. erl', line: 851]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 814]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl' , line: 240]}]}}}}}}}}}}}}}}
             (proxy 0.0.0-local.dev) lib/proxy/application.ex:28: Proxy.Application.start/2
             (kernel 8.5) application_master.erl:293: :application_master.start_it_old/4
```

**To Reproduce**
1. Open terminal on spawn_proxy/proxy folder and use this command to init the proxy: MIX_ENV=dev PROXY_CLUSTER_STRATEGY=gossip PROXY_DATABASE_TYPE=mysql  PROXY_DATABASE_POOL_SIZE=10 SPAWN_STATESTORE_KEY=3Jnb0hZiHIzHTOih7t2cTEPEpY98Tu1wvQkPfq/XwqE=  iex --name proxy_1@127.0.0.1 -S mix

2. Open another terminal on spawn_proxy/proxy folder and use this command to init the proxy: MIX_ENV=dev PROXY_CLUSTER_STRATEGY=gossip PROXY_DATABASE_TYPE=mysql  PROXY_DATABASE_POOL_SIZE=10 SPAWN_STATESTORE_KEY=3Jnb0hZiHIzHTOih7t2cTEPEpY98Tu1wvQkPfq/XwqE=  iex --name proxy_2@127.0.0.1 -S mix

**Expected behavior**
Proxy starts without errors when using the gossip strategy

**Screenshots**

![libcluster-failure](https://user-images.githubusercontent.com/342502/214701109-3e9d4ecd-ef7c-4749-ad12-a2a940569514.png)

**Spawn Operator (please complete the following information):**
 - Version 0.5.x

**Spawn Proxy (please complete the following information):**
 - Version 0.5.x

**Additional context**

I opened this Issue for historical record purposes only as I already submitted a PR to the libcluster project that fixes this issue. I'm just waiting for the merge of pr in the main branch and the release of a new version containing the correction to finish this bug in Spawn.

For more details see [here](https://github.com/bitwalker/libcluster/pull/187) and [here](https://github.com/bitwalker/libcluster/issues/184)

**Comment by bitwalker** [comment]
@sleipnir FYI a new release of libcluster has been pushed with your fix

**Comment by sleipnir** [comment]
Thanks a lot for the quick reply
