### ISSUE TITLE
[BUG] Proxy with two pods using node sdk in CrashLoopBackOff

### ISSUE THREAD

**Issue by eliasdarruda** [eigr/spawn#160]
in pod1:

```
2023-04-07 05:37:47.209 [wppbot@10.42.0.70]:[pid=<0.2688.0> ]:[error]:GenServer #PID<0.2688.0> terminating
** (stop) exited in: GenServer.stop(#PID<0.2689.0>, {:function_clause, [{Highlander, :handle_info, [{:EXIT, #PID<0.2689.0>, :shutdown}, %{child_spec: %{id: Actors.Actor.InvocationScheduler, restart: :transient, start: {Actors.Actor.InvocationScheduler, :start_link, []}}, pid: #PID<0.2689.0>}], [file: 'lib/highlander.ex', line: 90]}, {:gen_server, :try_dispatch, 4, [file: 'gen_server.erl', line: 1123]}, {:gen_server, :handle_msg, 6, [file: 'gen_server.erl', line: 1200]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 240]}]}, :infinity)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (elixir 1.14.0) lib/gen_server.ex:995: GenServer.stop/3
    (highlander 0.2.1) lib/highlander.ex:101: Highlander.terminate/2
    (stdlib 4.1) gen_server.erl:1161: :gen_server.try_terminate/3
    (stdlib 4.1) gen_server.erl:1351: :gen_server.terminate/10
    (stdlib 4.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: {:EXIT, #PID<0.2689.0>, :shutdown}
```

in pod2:

```
[info]:global: Name conflict terminating {Actors.Actor.InvocationScheduler, #PID<50461.2899.0>}
```

Also, it was thrown some warnings in libcluster

:[warning]:[libcluster:proxy] unable to connect to :"wppbot@10.42.0.66"

This is making one of the pods being in CrashLoopBackOff state

![image](https://user-images.githubusercontent.com/19327513/230548615-202e4cf1-175f-4f4b-848c-29cea05d16e4.png)

**Comment by sleipnir** [comment]
Hi @eliasdarruda The highlander message just indicates that one of the internal processes has been rebalanced between the pods. This is because this specific process is global for the ActorSystem in question.

The libcluster warning doesn't mean anything important. You should still be able to communicate normally between the pods.

**Comment by sleipnir** [comment]
Also let me know what the cluster events are for those pods.

kubectl get events and kubectl describe commands should help you with that

**Comment by eliasdarruda** [comment]
This happened because my cluster had low memory, so it couldn't properly startup

**Comment by sleipnir** [comment]
Thanks for feedback @eliasdarruda
