### ISSUE TITLE
[BUG] Different services not connecting on the same ActorSystem

### ISSUE THREAD

**Issue by sleipnir** [eigr/spawn#170]
**Describe the bug**
When we try to connect two different services (different deployments) to the same ActorSystem, the services cannot communicate.

Errors:

On the bootserver service
```
2023-04-13 20:52:51.789 [botserver@10.42.0.96]:[pid=<0.2743.0> ]:[warning]:[libcluster:proxy] unable to connect to :"botserver@10.42.0.97"
[18:00]
```

In wppbot service

```
2023-04-13 20:52:52.234 [wppbot@10.42.0.97]:[pid=<0.2743.0> ]:[warning]:[libcluster:proxy] unable to connect to :"wppbot@10.42.0.96"
```

It seems that libcluster's Kubernetes.DNS strategy is not properly configured or does not serve our purposes. Need to look more closely.

**To Reproduce**
1. Apply ActorSystem
2. Apply ActorHost with application 1 referencing the ActorSystem from step 1
3. Apply ActorHost with application 2referencing the ActorSystem from step 1

**Expected behavior**
Both ActorHosts connect successfully.

**Kubernetes (please complete the following information):**
 - Provider:  k3d or Any other

**Spawn Operator (please complete the following information):**
 - Version 0.5.x

**Spawn Proxy (please complete the following information):**
 - Version 0.5.x

**Comment by sleipnir** [comment]
Close this by [6af4e25](https://github.com/eigr/spawn/commit/6af4e25d610ae46b7a8fbf3aed9dcb383c61664b)

**Comment by sleipnir** [comment]
Wow 0/

**Comment by eliasdarruda** [comment]
nice work
