### ISSUE TITLE
[BUG] Broadcast multi system not receiving event

### ISSUE THREAD

**Issue by eliasdarruda** [eigr/spawn#224]
**Describe the bug**

When we are using two different actorhosts from two different systems and we use broadcast workflow to a specific topic, we don't receive the event on the subscribing actorhost

**Comment by sleipnir** [comment]
I suspect the bug is not just related to different actor systems. Maybe it's related to the subscription logic itself.

**Comment by sleipnir** [comment]
Fixed pubsub-nats dependency
