### ISSUE TITLE
[BUG] Error applying actorsystem

### ISSUE THREAD

**Issue by sleipnir** [eigr/spawn#228]
**Describe the bug**
Version 1.0.0-rc.17 introduced a bug at the time of creating the ActorSystem resource.
When we apply the yaml of the kind ActorSystem the Operator presents the following error in the log

```
** (RuntimeError) {"default/spawn-system", "spawn-eigr.io/v1", "Kind=ActorSystem, Action=:add"} - Failed applying descending (child) resource {"default/spawn-system-role", "rbac.authorization.k8s.io/v1", "Kind=Role"}. roles.rbac.authorization.k8s.io "spawn-system-role" is forbidden: User "system:serviceaccount:eigr-functions:spawn-operator" cannot patch resource "roles" in API group "rbac.authorization.k8s.io" in the namespace "default"
    (bonny 1.2.1) lib/bonny/axn.ex:406: anonymous fn/4 in Bonny.Axn.apply_descendants/2
    (elixir 1.14.0) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    (bonny 1.2.1) lib/bonny/axn.ex:382: Bonny.Axn.apply_descendants/2
    (spawn_operator 0.0.0-local.dev) lib/spawn_operator/operator.ex:1: SpawnOperator.Operator.pluggable_builder_call/2
    (bonny 1.2.1) lib/bonny/operator.ex:155: Bonny.Operator.run/4
    (elixir 1.14.0) lib/stream.ex:612: anonymous fn/4 in Stream.map/2
    (elixir 1.14.0) lib/enum.ex:4751: Enumerable.List.reduce/3
    (elixir 1.14.0) lib/stream.ex:1026: Stream.do_transform_inner_list/7
Function: &Bonny.Server.AsyncStreamRunner.run/2
    Args: [#Stream<[enum: #Function<60.124013645/2 in Stream.transform/3>, funs: [#Function<48.124013645/1 in Stream.map/2>, #Function<48.124013645/1 in Stream.map/2>]]>, nil]
```

After this error, it will not be possible to apply the ActorHost CRD because it will not be able to start the application and proxy containers.

**To Reproduce**
1. apply ActorSystem CRD
2. See Operator container logs

**Expected behavior**
That there are no errors and that the resources are successfully created.

**Spawn Operator (please complete the following information):**
 - Version 1.0.0-rc.17

**Spawn Proxy (please complete the following information):**
 - Version 1.0.0-rc.17

**Comment by mruoss** [comment]
So the way I understand it, in rc17 you must have introduced code to your HostActor controller which creates RBAC resources. The operator again needs the according RBAC configuration for this (permission to create roles, rolebindings, service accounts, etc.)

You would configure the controller's required RBAC permissions in [`rbac_rules/0` of the ActorHost controller](https://github.com/eigr/spawn/blob/main/spawn_operator/spawn_operator/lib/spawn_operator/controller/actor_host_controller.ex)

**Comment by mruoss** [comment]
Yeah I see now. I stumble upon this every single time. Look at [lines 11-14](https://github.com/eigr/spawn/blob/main/spawn_operator/spawn_operator/lib/spawn_operator/controller/actor_system_controller.ex) l. You put the "groupversion" in there. But for rbac permissions you only put the group. Compare the lines with lines 15ff!
