### ISSUE TITLE
Remove all anonymous functions from the hot path

### ISSUE THREAD

**Issue by sleipnir** [eigr/spawn#237]
It would be interesting if we removed all anonymous functions, or most of them, from our most used modules during our Actors' lifecycle.

Mainly those present in:

https://github.com/eigr/spawn/tree/main/lib/actors

**Comment by sleipnir** [comment]
By remove I mean refactor to use conventional named functions ;)

**Comment by ViniciusMRosa** [comment]
Hey folks, I'd like to contribute working on this issue!

**Comment by sleipnir** [comment]
Thank you @ViniciusMRosa let me know if you need some help on anything

**Comment by Cyytrus** [comment]
> Hey folks, I'd like to contribute working on this issue!

We can do a pair programming on that if you want!

**Comment by sleipnir** [comment]
@ViniciusMRosa @Cyytrus Do you still intend to go through with this?

**Comment by sleipnir** [comment]
Close due to inactivity
