### ISSUE TITLE
[Feat] Atomic Rollouts

### ISSUE THREAD

**Issue by sleipnir** [eigr/spawn#265]
**Describe the feature**
Allow version updates to be made atomically between different versions.

**Why would that be important to you?**
Prevents some types of crashes during rollouts.

**Additional context**
We can achieve this feature by simply adding a version attribute in the lookup mechanism. This way, any communication can only go from point A to point B if both are on the same version. The rest of the mechanism can be achieved with the help of k8s standard rollout strategies.

**Comment by eliasdarruda** [comment]
@sleipnir I don't think this is necessary anymore, WDYT? @sleipnir

**Comment by sleipnir** [comment]
@eliasdarruda I ended up thinking that the simplest way without needing a database query would be to simply rotate the erlang cookie for each rollout. This way the new pods will not be able to connect to the old ones. I think this would solve it and would only require a change to the operator.

wdyt?

**Comment by sleipnir** [comment]
After discussing in private with @eliasdarruda  and after reviewing the code and tests, I believe that this https://github.com/eigr/spawn/blob/725dccebf7069e0d9f17fbf1c074822cbdd5c316/lib/actors/actor/caller_producer.ex#L164 

is enough to guarantee consistency between rollouts and changing the types of data transmitted.

I will close this issue and if we need to revisit this item we will reopen it in the future.
