### ISSUE TITLE
Add an initialization callback to actors

### ISSUE THREAD

**Issue by sleipnir** [eigr/spawn#5]
The idea is to allow users to be able to register functions that should be called when the Process initializes for the first time, allowing the user to execute some code and initialize the Actor state.

Initially I didn't consider this because there are some risks in this type of functionality, such as the user overwriting a previous valid state with an invalid or empty state after a POD reboot.

But this can be circumvented using two strategies:

1. Always send the current state of the Actor in the Proxy as a parameter to the user function in order to allow the user to perform some type of validation.
2. In the function return a flag with the state update policy can be used to indicate whether the state should be overwritten or ignored. That is, if the Proxy already has a state saved in persistent storage and the flag indicates that the state should be overwritten then the proxy should update the state value every time. Otherwise just ignore the state value returned by the user function.

Below is an example of a user function that could be created for this functionality:

```java
@ActorEntity(name = "Joe", stateType = SomeState.class)
public class JoeActor {

    // This method is called once after the actor is registered. 
    // Subsequent activations do not trigger this callback
    @Init
    public Value init(ActorContext<SomeState> context) {
        // some code here
        ....
        return Value.ActorValue.at()
                .state(SomeState.getDefaultInstance())
                // Clear the state every time the function restarts
                .updateStrategy(PersistenceStrategy.OVERRIDE) // or default PersistenceStrategy.IGNORE
                .reply();
    }

    @Command
    public Value someMethod(SomeType data, ActorContext<SomeState> context) {
        // some code here
        ....
        return Value.ActorValue.at()
                // ....
                .reply();
    }
}
```

What do you think of this feature @marcellanz?

**Comment by sleipnir** [comment]
Is this really relevant? ping @marcellanz

**Comment by sleipnir** [comment]
> I think the proxy does know what state the Actor should be after she registered and therefore the proxy should have saying ultimately about when an actor gets to register towards the proxy. The actor could get thatbstate right away as part of the register response.

There are some problems with this return-of-state approach to the Actor Record call:

1. When I modeled the API, I did it so that the user could send as many as needed to be created. This implies that a state return should contain a list with the state of all Actors. This can make the entire http response unfeasible when too many actors are created at once.
2. The initialization of the Actor internally implies in some steps that make it difficult to obtain the state of the actor during its initialization. We use an initialization technique based on GenServer's handle_continue callbacks so that we don't crash the Supervisor of the Actors' processes when it needs to start several processes at once, this makes it possible to obtain the state we would have to make a second call to each Actor so that he could answer us about his state. This second call can burden the entire initialization system, which is why our actors initialization API was modeled to avoid having to return any information from the Actor itself during initialization.

For the above reasons, we proposed the "Init" API for this issue because, in this way, the BEAM Process responsible for the Host Actor would push its own state after its initialization has been completed to the Host Actor. Thus not needing any further research on its status.
I think the provocation of my previous question is more about something like "Does it make sense for me to provide this kind of callback" or "The user should handle this as he sees fit" ?

The semantics here also I think needs a correction if we continue with this idea. Let me explain. We are talking about Init here but actually the correct term should be wake up because in fact our actors activate and deactivate many times during their life cycle so it would be "initialized" many times. But by using the word init we give the user the idea that that initialization method/function/callback would be executed only when it registers, which would not be correct to assume. By switching to something like wake up (or up) we give the correct idea that that Host Actor function/method/callback would be executed every time the Actor process was activated. Which can even happen many times.

So again, sorry for the digression, the idea of ​​my question is is it worth it to offer this mechanism to the user or let them handle it in their own way?

**Comment by marcellanz** [comment]
How does an Actor, that we lost, get its state back to know? How can the proxy re-restablish state that was persisted, before an Actor dies?

**Comment by sleipnir** [comment]
> How does an Actor, that we lost, get its state back to know? How can the proxy re-restablish state that was persisted, before an Actor dies?

When initializing the Actor Process re-hydrates itself, in other words, fetches its state from persistent storage and loads it to its own heap

**Comment by sleipnir** [comment]
> .... How can the proxy re-restablish state that was persisted, before an Actor dies?

The second part of your question I didn't understand.
When the process dies, the only thing that happens is it tries to take a last synchronous snapshot of its state on the heap to persistent storage.

**Comment by sleipnir** [comment]
When it starts, it reads the data from storage to memory, and when it dies the process is the opposite, it writes the state of the memory to the persistent storage. An initialization callback as proposed here should occur at process startup and if and only if the Host Actor is of persistent type then the hook would be after the load_state callback of the Actor process

**Comment by sleipnir** [comment]
> When it starts, it reads the data from storage to memory, and when it dies the process is the opposite, it writes the state of the memory to the persistent storage. An initialization callback as proposed here should occur at process startup and if and only if the Host Actor is of persistent type then the hook would be after the load_state callback of the Actor process

The load_state callback happens inside a handle_continue so this is guaranteed to be the first thing that happens after an Actor Process is started/created/restarted. So it would be safe to call the Host function at this point in the process.

**Comment by sleipnir** [comment]
But I still insist that this shouldn't be used by the Host Function/Host Actor to create an actor state cache. As explained in other threads this is bad practice in our model. And therefore it must be avoided by the user. The init callback proposed here has a much more purpose of signaling to the user when a process is started/created/restarted than for the purpose of local caching.

**Comment by sleipnir** [comment]
@marcellanz I added simple support for this functionality. Check if you need anything to be included or excluded.
@eliasdarruda You can test this feature?
