### ISSUE TITLE
Error trying to create 5000 actors

### ISSUE THREAD

**Issue by danielchiovitti** [eigr/spawn#51]
When I try to create 5000 actors I'm getting the error "Killed" in the proxy.
With the help of @sleipnir I found this error:
Out of memory: Killed process 21551 (beam.smp) total-vm:29151740kB, anon-rss:16088396kB, file-rss:0kB, shmem-rss:66344kB, UID:1000 pgtables:48292kB oom_score_adj:0

Before the error the proxy created around 1000 actors

**Comment by sleipnir** [comment]
Some likely causes for actors to be so expensive could be the ActorRegistry stack or even the actor state...

https://github.com/eigr/spawn/blob/5c2319b3853ff0291f63aec685de780c3d501a84/apps/actors/lib/actors.ex#L35
https://github.com/eigr/spawn/blob/5c2319b3853ff0291f63aec685de780c3d501a84/apps/actors/lib/actors/actor/entity_supervisor.ex#L32

I don't remember creating many atoms in the code, so maybe they don't help with that. Anyway, we will have to inspect the processes to find out the cause of the bootleg.

@danielchiovitti Please when starting the proxy, before making any request, type the following command in iex:

```elixir
:observer_cli.start()
```

**Comment by danielchiovitti** [comment]
![image](https://user-images.githubusercontent.com/6583569/190644022-7cfa61dc-573f-416b-9bce-e06cdca4e927.png)

**Comment by sleipnir** [comment]
We have to lower the state of the actors and that will lower the pressure on the supervisor as well.

Just for the sake of knowledge I opened a call on Horde to investigate if it is possible to use the new Elixir feature for partitioned supervisors https://github.com/derekkraan/horde/issues/255. This does not have a direct relationship with the bug, but it does have an indirect one as the supervisor can be overwhelmed with the current architecture.
