### ISSUE TITLE
Integration with ElectricSQL

### ISSUE THREAD

**Issue by sleipnir** [eigr/spawn#6]
Add Vaxine Statemanager support

**Comment by sleipnir** [comment]
ping @thruflo

**Comment by sleipnir** [comment]
@thruflo any help here☺️?

**Comment by sleipnir** [comment]
It would be interesting to discuss some possible integration models with ElectricSql. Wdyt @thruflo @marcellanz @eliasdarruda

**Comment by thruflo** [comment]
Hey, yup, would be great to figure out the best integration path now we're getting to first base with https://electric-sql.com -- just copying from a DM:

> Yup, given you have the SQLite and MySQL adapters, now we run behind / alongside SQLite, I'm hoping it may be quite simple, e.g.: to run a SQLite and maybe initially an electric process as a sidecar to it. There are probably some nuances around sync and reactivity. Maybe it's a good time to setup a call to discuss, maybe next week?

Would you like to schedule a call or would you rather discuss async?

**Comment by thruflo** [comment]
Also noting from @sleipnir 

> In terms of adapters today we have adapters for MySQL, Postgres, MSSQL, and SQLite.
We are digging into Operator Controller and it is likely that it will be able to add any necessary containers in the same POD. But it is also possible to include ElectricSQL in the direct image of the Proxy container.
We are discussing a scenario where a browser-native JS client can be part of the Spawn mesh network. In this case maybe we could use the local-first capabilities in the brownser as well, but that I think would be a future discussion.

**Comment by sleipnir** [comment]
@marcellanz and @eliasdarruda do you have a free schedule to have this conversation?

**Comment by sleipnir** [comment]
ping @thruflo

**Comment by sleipnir** [comment]
@eliasdarruda It is likely that we will have to find an alternative to this by the release of version 1.
What do you think of us trying to use DetaCRDT's AWWLMap on top of sqlite?
