### ISSUE TITLE
MongoDB Support

### ISSUE THREAD

**Issue by sleipnir** [eigr/spawn#86]

**Comment by sleipnir** [comment]
Does anyone consider this still relevant?

**Comment by marcellanz** [comment]
I do.

**Comment by sleipnir** [comment]
> I do. I think this and other storage options can be open even if ATM no one is implementing them....

Fine.  Let´s leave this open

**Comment by sleipnir** [comment]
Closed as we will no longer support this statestore. https://github.com/eigr/spawn/pull/353
